version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - static_volume:/application/app/static/
      - media_volume:/application/app/static/docs
    expose:
      - 5000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/application/app/static/
      - media_volume:/application/app/static/docs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
      - ./app/cerbot/conf:/etc/letsencrypt
      - ./app/cerbot/www:/var/www/certbot
    ports:
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: