"""empty message

Revision ID: 552ad9c2c535
Revises: e60798f06fdc
Create Date: 2022-07-04 09:35:03.090458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552ad9c2c535'
down_revision = 'e60798f06fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('pdf_file', sa.VARCHAR(), nullable=True),
    sa.Column('pdf_thumbnail', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
