"""empty message

Revision ID: e60798f06fdc
Revises: 9f95b824384d
Create Date: 2022-06-08 09:57:18.579974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60798f06fdc'
down_revision = '9f95b824384d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index('ix_author_name')

    op.drop_table('author')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index('ix_book_author')
        batch_op.drop_index('ix_book_name')
        batch_op.drop_index('ix_book_photos')
        batch_op.drop_index('ix_book_price')

    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photos', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index('ix_book_price', ['price'], unique=False)
        batch_op.create_index('ix_book_photos', ['photos'], unique=False)
        batch_op.create_index('ix_book_name', ['name'], unique=False)
        batch_op.create_index('ix_book_author', ['author'], unique=False)

    op.create_table('author',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='author_pkey')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index('ix_author_name', ['name'], unique=False)

    # ### end Alembic commands ###
